### ISSUE TITLE
Option to run maturin within subfolder

### ISSUE THREAD

**Issue by benblack769** [messense/maturin-action#80] opened 2022-09-16 12:04 UTC
I like to arrange my rust/python projects like this:

- rust_lib
   - Cargo.toml
- python_wrapper
   - Cargo.toml (imports rust_lib as a local dependency)
   - pyproject.toml
- README.md

So that the rust project can potentially be deployed to crates.io without any of the python stuff. E.g. https://github.com/benblack769/box-intersect-py/tree/main/fast-box-lib-py

1. Is this a reasonable pattern? Is there any more standard alternative structure?
2. If so, then would it be possible to configure this action to run `maturin` from a particular subdirectory of the main project? Would this require any code changes? If so, I could submit a PR to add this functionality in.

**Comment by messense** [comment] 2022-09-16 12:06
Duplicate of https://github.com/messense/maturin-action/issues/11

**Closed by messense** 2022-09-16 12:06 UTC

**Comment by benblack769** [comment] 2022-09-17 03:19
Thanks, that was what I was looking for
